import {
  LayoutDashboard, Users, Building2, GitBranch, Briefcase,
  Package, FileText, Bell, BarChart2, ArrowLeftRight,
  TrendingUp, UserCheck, Shield, UserCog, ClipboardList,
  UserX, Building, ScrollText, UsersRound,
} from 'lucide-react';

export const ROUTES = {
  LOGIN:        '/login',
  DASHBOARD:    '/dashboard',
  EMPLOYEES:    '/employees',
  DEPARTMENTS:  '/departments',
  BRANCHES:     '/branches',
  DESIGNATIONS: '/designations',
  TEAMS:        '/teams',
  ASSETS:       '/assets',
  DOCUMENTS:    '/documents',
  TRANSFERS:    '/transfers',
  PROMOTIONS:   '/promotions',
  PROBATION:    '/probation',
  ONBOARDING:   '/onboarding',
  OFFBOARDING:  '/offboarding',
  SKILLS:       '/skills',
  USERS:        '/users',
  COMPANY:      '/company',
  NOTIFICATIONS:'/notifications',
  REPORTS:      '/reports',
  ROLES:        '/roles',
  AUDIT:        '/audit',
  PROFILE:      '/profile',
};

// Single source of truth — consumed by Sidebar and AppLayout
export const NAV_ITEMS = [
  { to: ROUTES.DASHBOARD,    icon: LayoutDashboard, labelKey: 'nav.dashboard',    group: null },
  { to: ROUTES.EMPLOYEES,    icon: Users,           labelKey: 'nav.employees',    group: 'People' },
  { to: ROUTES.USERS,        icon: UserCog,         labelKey: 'nav.users',        group: 'People' },
  { to: ROUTES.SKILLS,       icon: ClipboardList,   labelKey: 'nav.skills',       group: 'People' },
  { to: ROUTES.DEPARTMENTS,  icon: Building2,       labelKey: 'nav.departments',  group: 'Organization' },
  { to: ROUTES.BRANCHES,     icon: GitBranch,       labelKey: 'nav.branches',     group: 'Organization' },
  { to: ROUTES.DESIGNATIONS, icon: Briefcase,       labelKey: 'nav.designations', group: 'Organization' },
  { to: ROUTES.TEAMS,        icon: UsersRound,      labelKey: 'nav.teams',        group: 'Organization' },
  { to: ROUTES.COMPANY,      icon: Building,        labelKey: 'nav.company',      group: 'Organization' },
  { to: ROUTES.ASSETS,       icon: Package,         labelKey: 'nav.assets',       group: 'Operations' },
  { to: ROUTES.DOCUMENTS,    icon: FileText,        labelKey: 'nav.documents',    group: 'Operations' },
  { to: ROUTES.TRANSFERS,    icon: ArrowLeftRight,  labelKey: 'nav.transfers',    group: 'Lifecycle' },
  { to: ROUTES.PROMOTIONS,   icon: TrendingUp,      labelKey: 'nav.promotions',   group: 'Lifecycle' },
  { to: ROUTES.PROBATION,    icon: UserCheck,       labelKey: 'nav.probation',    group: 'Lifecycle' },
  { to: ROUTES.ONBOARDING,   icon: UserCheck,       labelKey: 'nav.onboarding',   group: 'Lifecycle' },
  { to: ROUTES.OFFBOARDING,  icon: UserX,           labelKey: 'nav.offboarding',  group: 'Lifecycle' },
  { to: ROUTES.NOTIFICATIONS,icon: Bell,            labelKey: 'nav.notifications',group: null },
  { to: ROUTES.REPORTS,      icon: BarChart2,       labelKey: 'nav.reports',      group: null },
  { to: ROUTES.ROLES,        icon: Shield,          labelKey: 'nav.roles',        group: 'Admin' },
  { to: ROUTES.AUDIT,        icon: ScrollText,      labelKey: 'nav.audit',        group: 'Admin' },
];
